### ISSUE TITLE
Getting `ParsingException: Could not store JavaScript player`

### ISSUE THREAD

**Issue by athulantonynp** [shalva97/NewValve#1]
Getting an error like the below. I tried to create a sample app to test this lib. Used the same code mentioned in the readme.

Error stack

````
FATAL EXCEPTION: main
                                                                                                    Process: athul.app.ktube, PID: 18893
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{athul.app.ktube/athul.app.ktube.MainActivity}: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not store JavaScript player
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3644)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not store JavaScript player
                                                                                                    	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.storePlayerJs(YoutubeStreamExtractor.java:1117)
                                                                                                    	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.initStsFromPlayerJsIfNeeded(YoutubeStreamExtractor.java:1185)
                                                                                                    	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:817)
                                                                                                    	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
                                                                                                    	at athul.app.ktube.MainActivity.runExtractor(MainActivity.kt:40)
                                                                                                    	at athul.app.ktube.MainActivity.onCreate(MainActivity.kt:33)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8342)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8321)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
                                                                                                    Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Embedded info did not provide YouTube player js url
                                                                                                    	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptUrl(YoutubeJavaScriptExtractor.java:116)
                                                                                                    	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:46)
                                                                                                    	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:65)
                                                                                                    	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.storePlayerJs(YoutubeStreamExtractor.java:1115)
                                                                                                    	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.initStsFromPlayerJsIfNeeded(YoutubeStreamExtractor.java:1185) 
                                                                                                    	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:817) 
                                                                                                    	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60) 
                                                                                                    	at athul.app.ktube.MainActivity.runExtractor(MainActivity.kt:40) 
                                                                                                    	at athul.app.ktube.MainActivity.onCreate(MainActivity.kt:33) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8342) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8321) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
````

Code
````
open class Application : Application() {

    override fun onCreate() {
        super.onCreate()
        initNewPipe()
    }
}

````

````
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            KTubeTheme {
                // A surface container using the 'background' color from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    Greeting("Android")
                }
            }
        }
        runExtractor()
    }

    private fun runExtractor(){
        val service = ServiceList.YouTube

        val extractor = service.getStreamExtractor("https://www.youtube.com/watch?v=3L6RDYFXURA")
        extractor.fetchPage()

        println("Video name: " + extractor.name)
        println("Uploader: " + extractor.uploaderName)
        println("Category: " + extractor.category)
        println("Likes: " + extractor.likeCount)
        println("Views: " + extractor.viewCount)
    }
}

````

**Comment by shalva97** [comment]
Do you have internet permission? Also you need to run http requests on IO thread on Android

```kotlin

GlobalScope.launch(Dispatchers.IO) {
    runExtractor()
}
```

**Comment by athulantonynp** [comment]
I tried running it in IO thread. Still same error. Also i do have the internet permission!!

**Comment by shalva97** [comment]
It's hard to say how to solve it because I can not reproduce it. One thing I can recommend is to add the [Extractor](https://github.com/TeamNewPipe/NewPipeExtractor) library directly to your project and if it still shows errors report it to them.
